# This config assumes we are in a directory where doko is checked out, but not inside it

version: "3.7"

services:
  database:
    image: mariadb:10.4.11-bionic
    restart: always
    environment:
      - MYSQL_DATABASE=doko
      - MYSQL_ROOT_PASSWORD=XXXXXXXCHANGEHERE
    volumes:
      - ./doko/server/src/database/schema:/docker-entrypoint-initdb.d:ro
      - ./mysql:/var/lib/mysql:rw
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  server:
    image: node:13.5.0-alpine3.10
    restart: always
    working_dir: /doko/server
    volumes:
      - ./doko:/doko:rw
    environment:
      - NODE_ENV=development
      - LOGUX_HOST=0.0.0.0
      - LOGUX_PORT=3030
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PW=XXXXXXXPLACEHERE
      - DB_NAME=doko
    entrypoint:
      - "yarn"
      - "start"
    ports:
      - "3434:3030"
